<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-rule</name>
  <uuid>2dac73f2-84e0-4562-b224-eb9d2755ea6b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add a new ML model output where
		the confidence is 0 , 
		the weight is 0 , 
		the rank is 0 to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
